<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IntentSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('web_intents')->truncate();

        DB::table('web_intents')->insert([

            [
                'nombre'               => 'Default Welcome Intent',
                'slug'                 => 'saludo',
                'dominio'              => 'general',
                'prioridad'            => 600,
                'eventos'              => json_encode(['WELCOME']),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([
                    'hola', 'buenas', 'buenos dias', 'buen dia', 'buenas tardes', 'buenas noches',
                    'hi', 'hello', 'saludos', 'muy buenas', 'que tal', 'como estas', 'ey', 'oye',
                    'inicio', 'menu', 'start', 'empezar', 'comenzar', 'volver',
                    'quiero informacion', 'necesito informacion',
                    'buenas tardes quisiera informacion sobre sus cursos',
                ]),
                'respuestas' => json_encode([]),
                'accion'  => 'saludo',
                'activo'  => 1,
                'orden'   => 1,
            ],

            [
                'nombre'               => 'Bot Presentacion',
                'slug'                 => 'presentacion',
                'dominio'              => 'general',
                'prioridad'            => 400,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([
                    'que eres', 'quien eres', 'que haces', 'eres un bot', 'eres humano',
                    'eres robot', 'eres una ia', 'como te llamas', 'cuales son tus funciones',
                    'en que me ayudas', 'que puedo hacer aqui', 'para que sirves',
                    'que tipo de asistente eres', 'como funciona esto',
                ]),
                'respuestas' => json_encode([
                    "🤖 Soy el asistente virtual del *MENTABIT*.\n\nEstoy programado para responder preguntas sobre:\n• Oferta académica (cursos y diplomados)\n• Proceso de inscripción\n• Costos y formas de pago\n• Docentes y horarios\n• Eventos e información institucional\n\nSi necesitas hablar con una persona, escribe *asesor*. 😊",
                ]),
                'accion'  => 'presentacion',
                'activo'  => 1,
                'orden'   => 2,
            ],

            [
                'nombre'               => 'Consulta Horarios',
                'slug'                 => 'horario',
                'dominio'              => 'general',
                'prioridad'            => 400,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([
                    'horario de atencion', 'a que hora atienden', 'hasta que hora',
                    'cuando atienden', 'horario de oficina', 'dias habiles',
                    'atienden sabado', 'atienden domingo', 'atienden hoy',
                    'esta abierto ahora', 'cuando abren', 'horario laboral',
                    'estan abiertos',
                ]),
                'respuestas' => json_encode([]),
                'accion'  => 'horario',
                'activo'  => 1,
                'orden'   => 3,
            ],

            [
                'nombre'               => 'Consulta Ubicacion',
                'slug'                 => 'ubicacion',
                'dominio'              => 'general',
                'prioridad'            => 400,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([
                    'donde estan', 'donde queda', 'como llego', 'como llegar',
                    'la direccion', 'cual es la direccion', 'donde se ubican',
                    'donde funciona el mentabit', 'que micro va', 'que trufi va',
                    'mapa', 'pin de ubicacion', 'google maps', 'como voy hasta ahi',
                    'sede', 'campus', 'instalaciones',
                ]),
                'respuestas' => json_encode([]),
                'accion'  => 'ubicacion',
                'activo'  => 1,
                'orden'   => 4,
            ],

            [
                'nombre'               => 'Solicitar Soporte Humano',
                'slug'                 => 'soporte',
                'dominio'              => 'general',
                'prioridad'            => 700,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([
                    'hablar con una persona', 'quiero hablar con alguien',
                    'atencion personalizada', 'atencion humana',
                    'comunicarme con un asesor', 'necesito asesor',
                    'hablar con alguien de verdad', 'hablar con humano',
                    'tengo una queja', 'quiero quejarme', 'quiero hacer un reclamo',
                    'necesito ayuda urgente', 'atencion al cliente', 'asesor',
                ]),
                'respuestas' => json_encode([]),
                'accion'  => 'soporte',
                'activo'  => 1,
                'orden'   => 5,
            ],

            [
                'nombre'               => 'Despedida',
                'slug'                 => 'despedida',
                'dominio'              => 'general',
                'prioridad'            => 500,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([
                    'chao', 'adios', 'hasta luego', 'bye', 'nos vemos', 'gracias hasta luego',
                    'hasta pronto', 'hasta la proxima', 'gracias por todo', 'muchas gracias',
                    'eso era todo', 'eso es todo', 'listo ya no necesito mas',
                    'ya me quedo claro', 'ya entendi', 'ok gracias',
                ]),
                'respuestas' => json_encode([
                    "¡Hasta pronto! 👋 Fue un placer ayudarte.\n\nRecuerda que puedes escribirnos cuando quieras. ¡Mucho éxito en tu formación! 🎓",
                    "¡Que te vaya muy bien! 😊 Si necesitas más información, aquí estaremos. ¡Hasta pronto! 👋",
                ]),
                'accion'  => 'despedida',
                'activo'  => 1,
                'orden'   => 6,
            ],

            [
                'nombre'               => 'Fallback - No Entendido',
                'slug'                 => 'fallback',
                'dominio'              => 'general',
                'prioridad'            => 100,
                'eventos'              => json_encode(['DEFAULT_FALLBACK']),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([]),
                'respuestas'           => json_encode([
                    "Disculpa, no entendí bien tu consulta. 🤔\n\nPuedes preguntarme sobre:\n📚 Cursos · 📝 Inscripciones · 💳 Pagos · 📍 Ubicación\n\nO escribe *menú* para ver todas las opciones.",
                    "No estoy seguro de cómo ayudarte con eso. 😕\n\nEscribe *menú* para ver lo que puedo hacer, o *asesor* si prefieres hablar con una persona.",
                ]),
                'accion'  => 'fallback',
                'activo'  => 1,
                'orden'   => 7,
            ],

            [
                'nombre'               => 'Consulta Cursos',
                'slug'                 => 'cursos',
                'dominio'              => 'academico',
                'prioridad'            => 500,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([['name' => 'cursos-flow', 'lifespan' => 3]]),
                'frases_entrenamiento' => json_encode([
                    'que cursos tienen', 'que programas ofrecen', 'cuales son sus diplomados',
                    'quiero ver los cursos disponibles', 'oferta academica', 'oferta educativa',
                    'catalogo de cursos', 'lista de cursos', 'cursos disponibles',
                    'quiero aprender', 'quiero capacitarme', 'quiero estudiar',
                    'me interesan sus cursos', 'informacion sobre cursos',
                    'cursos en linea', 'cursos online', 'formacion continua',
                    'tienen algo de marketing', 'tienen algo de administracion',
                    'tienen algo de salud', 'tienen algo de derecho',
                    'que diplomaturas tienen', 'programas de posgrado',
                ]),
                'respuestas' => json_encode([]),
                'accion'  => 'cursos',
                'activo'  => 1,
                'orden'   => 8,
            ],

            [
                'nombre'               => 'Consulta Cursos - Me Interesa',
                'slug'                 => 'cursos_interes',
                'dominio'              => 'academico',
                'prioridad'            => 650,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode(['cursos-flow']),
                'output_contexts'      => json_encode([
                    ['name' => 'cursos-flow', 'lifespan' => 2],
                    ['name' => 'inscripcion-flow', 'lifespan' => 3],
                ]),
                'frases_entrenamiento' => json_encode([
                    'ese me interesa', 'me interesa ese curso', 'quiero ese',
                    'dime mas de ese', 'mas informacion', 'cuanto cuesta ese',
                    'como me inscribo en ese', 'quiero inscribirme en ese',
                    'el primero', 'el segundo', 'el tercero', 'el cuarto',
                ]),
                'respuestas' => json_encode([
                    "¡Excelente elección! 😊\n\nPara completar tu inscripción necesito algunos datos.\n\n¿Cuál es tu *nombre completo*?",
                    "Perfecto, te ayudo con la inscripción. 📝\n\n¿Cuál es tu *nombre completo*?",
                    "¡Genial! Vamos a iniciar tu proceso de inscripción. 🎓\n\n¿Cuál es tu *nombre completo*?",
                ]),
                'accion'  => 'inscripcion_flow',
                'activo'  => 1,
                'orden'   => 9,
            ],

            [
                'nombre'               => 'Proceso Inscripcion',
                'slug'                 => 'inscripciones',
                'dominio'              => 'academico',
                'prioridad'            => 500,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([['name' => 'inscripcion-flow', 'lifespan' => 3]]),
                'frases_entrenamiento' => json_encode([
                    'como me inscribo', 'quiero inscribirme', 'como me registro',
                    'proceso de inscripcion', 'requisitos para inscribirse',
                    'que documentos necesito', 'documentos para inscripcion',
                    'donde me inscribo', 'cuando cierran inscripciones',
                    'todavia hay cupos', 'quedan vacantes', 'hay plazas disponibles',
                    'como puedo postular', 'quiero anotarme', 'quiero postular',
                    'formulario de inscripcion', 'inscripcion en linea', 'preinscripcion',
                ]),
                'respuestas' => json_encode([]),
                'accion'  => 'inscripciones',
                'activo'  => 1,
                'orden'   => 10,
            ],

            [
                'nombre'               => 'Inscripcion - Confirmar',
                'slug'                 => 'inscripcion_confirmar',
                'dominio'              => 'academico',
                'prioridad'            => 650,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode(['inscripcion-flow']),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([
                    'si', 'si por favor', 'dale', 'listo', 'procede',
                    'adelante', 'procedemos', 'confirmado', 'si inscribeme',
                    'si me anoto', 'va', 'vamos', 'de acuerdo', 'correcto',
                    'si asi es', 'afirmativo', 'claro que si', 'acepto', 'confirmo',
                ]),
                'respuestas' => json_encode([
                    "✅ ¡Perfecto! Para completar tu inscripción, comunícate con nosotros:\n\n📞 *WhatsApp:* este mismo número en horario de atención\n📧 *Email:* info@mentabit.edu.bo\n🏢 *Presencial:* visítanos en horario hábil\n\n¿Hay algo más en que pueda ayudarte?",
                    "📝 Anotado. Para formalizar tu inscripción puedes:\n\n• Visitar nuestras *oficinas* en horario de atención\n• Escribir al *email* info@mentabit.edu.bo\n• Contactar a un *asesor* por este medio\n\n¡Con gusto te guiamos en los siguientes pasos! 😊",
                ]),
                'accion'  => 'inscripcion_confirmar',
                'activo'  => 1,
                'orden'   => 11,
            ],

            [
                'nombre'               => 'Inscripcion - Cancelar / No',
                'slug'                 => 'inscripcion_cancelar',
                'dominio'              => 'academico',
                'prioridad'            => 600,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode(['inscripcion-flow']),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([
                    'no', 'no gracias', 'ahora no', 'tal vez despues', 'cancelar',
                    'no quiero', 'prefiero no', 'lo voy a pensar', 'me lo pienso',
                    'otro momento', 'quiza despues', 'no por ahora',
                ]),
                'respuestas' => json_encode([
                    "No hay problema 😊 Cuando estés listo/a, aquí estaremos.\n\nEscribe *menú* para ver otras opciones o *cursos* para volver a revisar la oferta académica.",
                ]),
                'accion'  => 'inscripcion_cancelar',
                'activo'  => 1,
                'orden'   => 12,
            ],

            [
                'nombre'               => 'Consulta Modalidad',
                'slug'                 => 'modalidad',
                'dominio'              => 'academico',
                'prioridad'            => 450,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([
                    'es online', 'es presencial', 'modalidad del curso', 'como son las clases',
                    'clases virtuales', 'clases a distancia', 'clases en vivo', 'clases hibridas',
                    'hay clases los fines de semana', 'horario de clases', 'cuando son las clases',
                    'cuanto duran las clases', 'cuantas horas', 'duracion del diplomado',
                    'cuanto dura el curso', 'cuantos modulos', 'cuantos meses',
                ]),
                'respuestas' => json_encode([
                    "🖥️ *Modalidades disponibles:*\n\n• *Presencial* — en nuestras instalaciones\n• *Virtual (en línea)* — clases en vivo por videoconferencia\n• *Mixta (semipresencial)* — combinación de ambas\n\nLa duración varía según el programa (2 a 6 meses).\n\n¿Te interesa algún programa en específico? 😊",
                ]),
                'accion'  => 'modalidad',
                'activo'  => 1,
                'orden'   => 13,
            ],

            [
                'nombre'               => 'Consulta Certificados',
                'slug'                 => 'certificados',
                'dominio'              => 'academico',
                'prioridad'            => 450,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([
                    'dan certificado', 'tienen certificado', 'que certificado entregan',
                    'certificado de aprobacion', 'certificado de participacion',
                    'diploma', 'acreditacion', 'certificado tiene validez',
                    'el certificado es valido', 'como es el certificado',
                    'entregan titulo', 'dan diploma', 'es reconocido',
                    'tiene validez oficial', 'certificado avalado',
                    'donde verifico mi certificado', 'como verifico',
                ]),
                'respuestas' => json_encode([
                    "🎓 *Certificación MENTABIT*\n\nAl concluir y aprobar el programa recibes:\n\n✅ *Certificado de aprobación* emitido por MENTABIT\n✅ *Diploma* con código QR de verificación\n✅ *Verificación online* en mentabit.edu.bo\n\nLos certificados tienen validez académica y profesional. 😊",
                ]),
                'accion'  => 'certificados',
                'activo'  => 1,
                'orden'   => 14,
            ],

            [
                'nombre'               => 'Consulta Pagos',
                'slug'                 => 'pagos',
                'dominio'              => 'academico',
                'prioridad'            => 500,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([['name' => 'pagos-flow', 'lifespan' => 3]]),
                'frases_entrenamiento' => json_encode([
                    'cuanto cuesta', 'cual es el precio', 'cuanto vale', 'cuanto cobran',
                    'cual es el costo', 'cuanto es la cuota', 'cuanto es la mensualidad',
                    'como pago', 'formas de pago', 'metodos de pago',
                    'se puede pagar en cuotas', 'acepta tarjeta',
                    'pago en linea', 'deposito bancario', 'transferencia bancaria',
                    'tienen becas', 'dan descuentos', 'precio especial',
                    'es muy caro', 'sale caro', 'beca', 'descuento',
                ]),
                'respuestas' => json_encode([]),
                'accion'  => 'pagos',
                'activo'  => 1,
                'orden'   => 15,
            ],

            [
                'nombre'               => 'Pagos - Metodo Especifico',
                'slug'                 => 'pagos_metodo',
                'dominio'              => 'academico',
                'prioridad'            => 650,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode(['pagos-flow']),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([
                    'efectivo', 'en cash', 'pago en efectivo',
                    'tarjeta de credito', 'tarjeta de debito', 'con tarjeta',
                    'transferencia', 'deposito', 'por transferencia',
                    'qr', 'pago qr', 'tigo money', 'billetera movil',
                    'cuotas', 'a plazos', 'financiamiento', 'en cuotas mensuales',
                    'metodos de pago',
                ]),
                'respuestas' => json_encode([
                    "💳 *Métodos de pago aceptados:*\n\n• 💵 *Efectivo* (en oficina)\n• 📱 *QR / Billetera móvil* (Tigo Money, SimpleBank)\n• 🏦 *Transferencia bancaria* (BNB, BCP, Banco Unión)\n• 💳 *Tarjeta de débito/crédito*\n• 📅 *Pago en cuotas* (consultar con un asesor)\n\n¿Necesitas más información? Escribe *asesor*. 😊",
                    "🏦 *Formas de pago:*\n\n✅ Efectivo · ✅ QR · ✅ Transferencia · ✅ Tarjeta\n\nTambién existe la opción de *cuotas mensuales* según el programa. Consulta con un asesor los detalles. 😊",
                ]),
                'accion'  => 'pagos_metodo',
                'activo'  => 1,
                'orden'   => 16,
            ],

            [
                'nombre'               => 'Consulta Docentes',
                'slug'                 => 'docentes',
                'dominio'              => 'academico',
                'prioridad'            => 400,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([['name' => 'docentes-flow', 'lifespan' => 2]]),
                'frases_entrenamiento' => json_encode([
                    'quien da las clases', 'quienes son los profesores',
                    'quien imparte el curso', 'cuerpo docente', 'planta docente',
                    'curriculum del profesor', 'experiencia del docente',
                    'que profesores tienen', 'quienes son sus docentes',
                    'profesores disponibles', 'quienes dan clases',
                    'listado de profesores', 'datos del profesor',
                ]),
                'respuestas' => json_encode([]),
                'accion'  => 'docentes',
                'activo'  => 1,
                'orden'   => 17,
            ],

            [
                'nombre'               => 'Consulta Requisitos',
                'slug'                 => 'requisitos',
                'dominio'              => 'academico',
                'prioridad'            => 450,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([
                    'que requisitos necesito', 'que documentos piden', 'que me piden para inscribirme',
                    'cuales son los requisitos', 'necesito tener titulo', 'se puede sin titulo',
                    'tengo que ser profesional', 'puedo estudiar siendo estudiante',
                    'se puede cursar siendo bachiller', 'requisito de ingreso',
                    'necesito experiencia', 'que perfil buscan',
                ]),
                'respuestas' => json_encode([
                    "📋 *Requisitos generales de inscripción:*\n\n• Fotocopia de Cédula de Identidad\n• Fotocopia de título de bachiller o universitario\n• Fotografía 3×3 reciente\n• Formulario de inscripción (se completa en oficina o en línea)\n\nAlgunos programas tienen requisitos adicionales. Escribe *inscripcion* para iniciar. 📝",
                ]),
                'accion'  => 'requisitos',
                'activo'  => 1,
                'orden'   => 18,
            ],

            [
                'nombre'               => 'Seguimiento Inscripcion',
                'slug'                 => 'seguimiento',
                'dominio'              => 'academico',
                'prioridad'            => 500,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([['name' => 'seguimiento-flow', 'lifespan' => 2]]),
                'frases_entrenamiento' => json_encode([
                    'consultar mi inscripcion', 'como va mi inscripcion',
                    'estado de mi inscripcion', 'revisar mi solicitud', 'ya me inscribi',
                    'cuando me confirman', 'ya envie mis datos',
                    'seguimiento de inscripcion', 'consultar con mi ci',
                ]),
                'respuestas' => json_encode([
                    "🔍 Puedo consultarte el estado de tu inscripción.\n\n¿Cuál es tu *número de Cédula de Identidad*?",
                ]),
                'accion'  => 'seguimiento',
                'activo'  => 1,
                'orden'   => 19,
            ],

            [
                'nombre'               => 'Consulta Noticias',
                'slug'                 => 'noticias',
                'dominio'              => 'contenido',
                'prioridad'            => 300,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([
                    'que hay de nuevo', 'ultimas noticias', 'novedades',
                    'noticias del mentabit', 'noticias recientes',
                    'actualizaciones', 'noticias de hoy', 'algo nuevo', 'blog',
                ]),
                'respuestas' => json_encode([]),
                'accion'  => 'noticias',
                'activo'  => 1,
                'orden'   => 20,
            ],

            [
                'nombre'               => 'Consulta Boletines',
                'slug'                 => 'boletines',
                'dominio'              => 'contenido',
                'prioridad'            => 300,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([
                    'boletin', 'boletines', 'boletin academico', 'boletin mentabit',
                    'boletin mensual', 'ultimo boletin', 'revista', 'circular', 'comunicado',
                ]),
                'respuestas' => json_encode([]),
                'accion'  => 'boletines',
                'activo'  => 1,
                'orden'   => 21,
            ],

            [
                'nombre'               => 'Consulta Eventos',
                'slug'                 => 'eventos',
                'dominio'              => 'contenido',
                'prioridad'            => 400,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([
                    'que eventos hay', 'proximos eventos', 'actividades programadas',
                    'seminarios disponibles', 'talleres proximos', 'conferencias',
                    'webinar', 'charlas', 'jornada academica', 'graduacion',
                    'calendario de eventos', 'agenda de actividades',
                ]),
                'respuestas' => json_encode([]),
                'accion'  => 'eventos',
                'activo'  => 1,
                'orden'   => 22,
            ],

            [
                'nombre'               => 'Consulta Redes Sociales',
                'slug'                 => 'redes_sociales',
                'dominio'              => 'contenido',
                'prioridad'            => 300,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([
                    'facebook', 'instagram', 'tiktok', 'youtube', 'redes sociales',
                    'pagina de facebook', 'cuenta de instagram', 'canal de youtube',
                    'sigues en redes', 'links de redes', 'tienen facebook', 'tienen instagram',
                ]),
                'respuestas' => json_encode([
                    "📱 *Síguenos en redes sociales:*\n\n📘 Facebook: /MENTABIT\n📸 Instagram: @mentabit_oficial\n▶️ YouTube: MENTABIT\n\nO visita nuestra web *mentabit.edu.bo* para todos los enlaces. 😊",
                ]),
                'accion'  => 'redes_sociales',
                'activo'  => 1,
                'orden'   => 23,
            ],

            [
                'nombre'               => 'Consulta Convenios',
                'slug'                 => 'convenios',
                'dominio'              => 'contenido',
                'prioridad'            => 350,
                'eventos'              => json_encode([]),
                'input_contexts'       => json_encode([]),
                'output_contexts'      => json_encode([]),
                'frases_entrenamiento' => json_encode([
                    'tienen convenios', 'con que instituciones tienen convenio',
                    'convenios con universidades', 'acuerdos institucionales',
                    'alianzas', 'instituciones aliadas', 'con quien trabajan',
                    'estan reconocidos por', 'afiliados a', 'miembros de',
                ]),
                'respuestas' => json_encode([
                    "🤝 *Convenios MENTABIT*\n\nContamos con convenios y alianzas estratégicas con instituciones nacionales e internacionales.\n\nPara más información sobre convenios específicos, visita *mentabit.edu.bo* o contáctanos directamente. 😊",
                ]),
                'accion'  => 'convenios',
                'activo'  => 1,
                'orden'   => 24,
            ],

        ]);
    }
}
