<?php

namespace App\Http\Controllers;

use OpenApi\Attributes as OA;

#[OA\Info(
    title: 'MENTABIT API',
    version: '1.0.0',
    description: 'API REST del Centro de Formación Continua (MENTABIT). Gestión académica de cursos, diplomados, programas, inscripciones, notas, pagos, docentes, certificados y contenido del portal web institucional.'
)]
#[OA\Server(url: '/api', description: 'Auth / Integraciones')]
#[OA\Server(url: '/api/v1', description: 'API v1 — Recursos principales')]
#[OA\SecurityScheme(
    securityScheme: 'sanctum',
    type: 'http',
    scheme: 'bearer',
    bearerFormat: 'JWT',
    description: 'Token Bearer de Laravel Sanctum. Obtenerlo con POST /api/auth/login'
)]
#[OA\Tag(name: 'Auth', description: 'Autenticación y gestión de sesión')]
#[OA\Tag(name: 'Usuarios', description: 'Gestión de usuarios del sistema')]
#[OA\Tag(name: 'Roles', description: 'Roles y asignación de permisos')]
#[OA\Tag(name: 'Permisos', description: 'Permisos granulares del sistema')]
#[OA\Tag(name: 'Etiquetas', description: 'Etiquetas para clasificar contenido')]
#[OA\Tag(name: 'Ajustes', description: 'Ajustes clave-valor del sistema')]
#[OA\Tag(name: 'Settings', description: 'Configuración avanzada (Spatie Settings)')]
#[OA\Tag(name: 'Redes Sociales', description: 'Links de redes sociales institucionales')]
#[OA\Tag(name: 'Banners Portal', description: 'Banners del portal web')]
#[OA\Tag(name: 'Configuración Sitio', description: 'Configuración general del sitio web')]
#[OA\Tag(name: 'Dashboard', description: 'Estadísticas del panel de control')]
#[OA\Tag(name: 'Upload', description: 'Carga de imágenes y archivos')]
#[OA\Tag(name: 'Eventos', description: 'Gestión de eventos académicos e institucionales')]
#[OA\Tag(name: 'Preguntas Frecuentes', description: 'Preguntas frecuentes del módulo académico')]
#[OA\Tag(name: 'FAQs', description: 'FAQs del portal web general')]
#[OA\Tag(name: 'Mensajes de Contacto', description: 'Mensajes del formulario de contacto')]
#[OA\Tag(name: 'Testimonios', description: 'Testimonios de estudiantes y egresados')]
#[OA\Tag(name: 'Aliados', description: 'Aliados estratégicos de la institución')]
#[OA\Tag(name: 'Docentes Perfil', description: 'Perfiles públicos de docentes')]
#[OA\Tag(name: 'Popups', description: 'Ventanas emergentes del portal')]
#[OA\Tag(name: 'WhatsApp Grupos', description: 'Grupos de WhatsApp por curso')]
#[OA\Tag(name: 'Galería Categorías', description: 'Categorías de la galería de fotos')]
#[OA\Tag(name: 'Galería Videos', description: 'Galería de videos institucionales')]
#[OA\Tag(name: 'Descargables', description: 'Documentos descargables del portal')]
#[OA\Tag(name: 'Calendario Académico', description: 'Calendario de actividades académicas')]
#[OA\Tag(name: 'Cifras Institucionales', description: 'Cifras e indicadores institucionales')]
#[OA\Tag(name: 'Hitos Institucionales', description: 'Hitos históricos de la institución')]
#[OA\Tag(name: 'Notas de Prensa', description: 'Notas y comunicados de prensa')]
#[OA\Tag(name: 'Acreditaciones', description: 'Acreditaciones y reconocimientos')]
#[OA\Tag(name: 'Descuentos y Promociones', description: 'Descuentos y promociones académicas')]
#[OA\Tag(name: 'Suscriptores', description: 'Suscriptores al boletín informativo')]
#[OA\Tag(name: 'Redirecciones', description: 'Redirecciones URL del portal')]
#[OA\Tag(name: 'Grados Académicos', description: 'Catálogo de grados académicos')]
#[OA\Tag(name: 'Expedido', description: 'Tipos de expedición de documentos')]
#[OA\Tag(name: 'WhatsApp Admin', description: 'Gestión de conversaciones y envíos por WhatsApp')]
#[OA\Tag(name: 'Asesores', description: 'Asesores de admisión y soporte')]
#[OA\Tag(name: 'Cursos', description: 'Cursos y diplomados ofertados')]
#[OA\Tag(name: 'Categorías Programa', description: 'Categorías y áreas de los programas')]
#[OA\Tag(name: 'Campos Categoría', description: 'Campos personalizados por categoría de programa')]
#[OA\Tag(name: 'Tipos Programa', description: 'Tipos de programas académicos')]
#[OA\Tag(name: 'Tipos Postgrado', description: 'Tipos de postgrado')]
#[OA\Tag(name: 'Carreras', description: 'Carreras universitarias de los estudiantes')]
#[OA\Tag(name: 'Materias', description: 'Materias y asignaturas')]
#[OA\Tag(name: 'Materias Plan', description: 'Relación materia-plan de estudios')]
#[OA\Tag(name: 'Planes Académicos', description: 'Planes de estudio')]
#[OA\Tag(name: 'Programas Académicos', description: 'Programas académicos vigentes')]
#[OA\Tag(name: 'Imparticiones', description: 'Apertura de cursos (imparticiones)')]
#[OA\Tag(name: 'Usuarios Académicos', description: 'Estudiantes y docentes registrados')]
#[OA\Tag(name: 'Inscripciones', description: 'Inscripciones a cursos y programas')]
#[OA\Tag(name: 'Formularios', description: 'Formularios dinámicos de inscripción')]
#[OA\Tag(name: 'Notas Académicas', description: 'Calificaciones de los estudiantes')]
#[OA\Tag(name: 'Horarios Académicos', description: 'Horarios de clases')]
#[OA\Tag(name: 'Grupos Académicos', description: 'Grupos de estudiantes')]
#[OA\Tag(name: 'Requisitos Académicos', description: 'Requisitos de admisión y titulación')]
#[OA\Tag(name: 'Catálogo Académico', description: 'Catálogos genéricos del módulo académico')]
#[OA\Tag(name: 'Configuración Académica', description: 'Configuración del módulo académico')]
#[OA\Tag(name: 'Historial', description: 'Historial académico de los estudiantes')]
#[OA\Tag(name: 'Reseñas', description: 'Reseñas y valoraciones de programas')]
#[OA\Tag(name: 'Pagos Académicos', description: 'Registro de pagos de matrícula y cuotas')]
#[OA\Tag(name: 'Fechas Pago', description: 'Calendario de fechas de pago')]
#[OA\Tag(name: 'Fechas Documento', description: 'Fechas de entrega de documentos')]
#[OA\Tag(name: 'Ingresos', description: 'Registro de ingresos económicos')]
#[OA\Tag(name: 'Pasarela Pagos', description: 'Webhook de confirmación de pagos online')]
#[OA\Tag(name: 'Cert. Plantillas', description: 'Plantillas de certificados con diseño')]
#[OA\Tag(name: 'Cert. Campos', description: 'Campos y posiciones en plantillas de certificado')]
#[OA\Tag(name: 'Lista Aprobados', description: 'Lista oficial de estudiantes aprobados')]
#[OA\Tag(name: 'Certificados', description: 'Certificados generados con código QR')]
#[OA\Tag(name: 'Cert. Verificaciones', description: 'Verificaciones públicas de certificados')]
#[OA\Tag(name: 'Certificados Modelo', description: 'Modelos base de certificados')]
#[OA\Tag(name: 'Usuarios Plan', description: 'Asignación de usuarios a planes')]
#[OA\Tag(name: 'Usuarios Programa', description: 'Asignación de usuarios a programas')]
#[OA\Tag(name: 'Usuarios Tipo Programa', description: 'Tipos de programa por usuario')]
#[OA\Tag(name: 'Usuarios Plan Doc', description: 'Documentos del plan por usuario')]
#[OA\Tag(name: 'Usuarios Moodle', description: 'Cuentas Moodle de los estudiantes')]
#[OA\Tag(name: 'Artículos', description: 'Artículos académicos y noticias')]
#[OA\Tag(name: 'Boletines', description: 'Boletines informativos')]
#[OA\Tag(name: 'Fotos', description: 'Galería de fotos')]
#[OA\Tag(name: 'Tesis', description: 'Repositorio de tesis')]
#[OA\Tag(name: 'Monografías', description: 'Repositorio de monografías')]
#[OA\Tag(name: 'Revistas', description: 'Revistas institucionales')]
#[OA\Tag(name: 'Revistas Científicas', description: 'Revistas científicas indexadas')]
#[OA\Tag(name: 'Documentos Académicos', description: 'Documentos requeridos en el proceso académico')]
#[OA\Tag(name: 'Ayudas', description: 'Ayudas económicas y becas')]
#[OA\Tag(name: 'Cartas', description: 'Cartas generadas para estudiantes')]
#[OA\Tag(name: 'Cartas Modelo', description: 'Modelos de cartas institucionales')]
#[OA\Tag(name: 'Cartas Generadas', description: 'Cartas generadas automáticamente')]
#[OA\Tag(name: 'Formularios Académicos', description: 'Formularios del proceso académico')]
#[OA\Tag(name: 'Formularios Inscripción', description: 'Formularios de inscripción')]
#[OA\Tag(name: 'Tests Académicos', description: 'Tests y evaluaciones')]
#[OA\Tag(name: 'Hojas Evaluación', description: 'Hojas de evaluación docente')]
#[OA\Tag(name: 'Archivos Académicos', description: 'Archivos adjuntos del módulo académico')]
#[OA\Tag(name: 'Páginas Académicas', description: 'Páginas del portal académico')]
#[OA\Tag(name: 'Bloques Ajustables', description: 'Bloques de contenido configurables')]
#[OA\Tag(name: 'Bloques Plantilla', description: 'Plantillas de bloques de contenido')]
#[OA\Tag(name: 'Secciones Bloque', description: 'Secciones dentro de bloques de plantilla')]
#[OA\Tag(name: 'Reg. Componentes', description: 'Registro de componentes del portal')]
#[OA\Tag(name: 'Reg. Formularios', description: 'Registro de formularios del portal')]
#[OA\Tag(name: 'Funcionalidades Formulario', description: 'Funcionalidades de los formularios')]
#[OA\Tag(name: 'Formatos Hoja Solicitud', description: 'Formatos de hoja de solicitud')]
#[OA\Tag(name: 'Menús Académicos', description: 'Estructura de menús del portal académico')]
#[OA\Tag(name: 'Módulos Académicos', description: 'Módulos funcionales del portal académico')]
#[OA\Tag(name: 'Moodle Config', description: 'Configuración de instancias Moodle')]
#[OA\Tag(name: 'Moodle Cursos', description: 'Gestión de cursos en Moodle')]
#[OA\Tag(name: 'Moodle Usuarios', description: 'Gestión de usuarios en Moodle')]
#[OA\Tag(name: 'Zoom', description: 'Gestión de reuniones y grabaciones en Zoom')]
#[OA\Tag(name: 'WhatsApp Webhook', description: 'Webhook de mensajes entrantes de WhatsApp')]
#[OA\Tag(name: 'Telegram Webhook', description: 'Webhook de mensajes entrantes de Telegram')]
#[OA\Tag(name: 'Portal', description: 'Endpoints públicos del portal web (requieren API Key)')]
#[OA\Tag(name: 'Público', description: 'Endpoints totalmente públicos (sin autenticación)')]
abstract class Controller
{
}
